spring.application.name=SpringSecurityProject

spring.security.user.name=Sudheer
spring.security.user.password=Sudheer@123

# ===============================
# DATASOURCE (ORACLE)
# ===============================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREE
spring.datasource.username=sudheer
spring.datasource.password=sudheer123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# HIKARI CONNECTION POOL
# ===============================
spring.datasource.hikari.pool-name=HikariOraclePool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true